#!/usr/bin/env python3
"""Generate the reference pages of ``docs/site/`` from the code they document.

Hand-written reference documentation drifts the day it is written. Every page this
script owns is derived from the real objects — the tool registry, the settings
loader, the hook events, the subagent definitions, the provider adapter table — so a
page cannot disagree with the code without a test going red.

The pattern is copied from ``scripts/sync_typecheck_paths.py`` and
``scripts/generate_readme_stats.py``: write in place by default, ``--check`` to fail
when a file on disk differs from what the code now says::

    python docs/site/generate.py           # rewrite the generated pages
    python docs/site/generate.py --check   # exit 1 if any page is stale

``tests/telemetry/test_ronin_telemetry_docsite.py`` runs the same comparison, so the
staleness gate holds even where this script is not wired into CI.

**Only reference pages are generated.** ``index.md`` and ``quickstart.md`` are prose
about how to use the thing, which no amount of introspection produces; they are
hand-written and carry no generated marker. Every generated page carries
:data:`MARKER` on its first line so nobody edits one by hand and loses the edit.

There is no static-site generator here on purpose: the repository has none already
(no mkdocs, no sphinx, no docusaurus), and adding one to render seven markdown files
would be a build dependency in exchange for a nav bar. Plain markdown renders on
GitHub, in an editor, and in every static host, and it is what the rest of ``docs/``
already is.

No measured numbers appear on any page. Counts that are derived by walking a real
object — "13 tools", "5 hook events" — are facts about this checkout and are
recomputed here; anything that would require running a model or a benchmark is not
stated at all.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Awaitable, Mapping, Sequence
from pathlib import Path

SITE = Path(__file__).resolve().parent
ROOT = SITE.parent.parent

# The generator runs as a script from a checkout, where `src/` is only on the path
# because pytest's `pythonpath` puts it there. Doing it here keeps `python
# docs/site/generate.py` working from a bare clone with no install step.
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

from ronin.agents.definitions import (  # noqa: E402
    AGENTS_SUBDIR,
    BUILTIN_AGENTS,
    KNOWN_KEYS,
    MODEL_ROLES,
    MUTATING_TOOL_NAMES,
    REQUIRED_KEYS,
)
from ronin.agents.hooks import (  # noqa: E402
    BLOCK_EXIT_CODE,
    BLOCKING_EVENTS,
    DEFAULT_TIMEOUT_SECONDS,
    MATCH_ALL,
    MAX_HOOK_OUTPUT_CHARS,
    TOOL_EVENTS,
    HookEvent,
    HookOutcome,
    event_payload,
)
from ronin.cli.main import Command as CliCommand  # noqa: E402
from ronin.cli.spine import (  # noqa: E402
    CACHE_SUBDIR,
    COMMANDS_SUBDIR,
    HOOKS_FILENAME,
    RONIN_DIRNAME,
)
from ronin.core.types import DangerLevel, Mode, ToolSpec  # noqa: E402
from ronin.mcp.config import MCP_CONFIG_RELATIVE_PATH  # noqa: E402
from ronin.persistence.transcript import SESSIONS_SUBDIR  # noqa: E402
from ronin.providers.mlx_local import LOCAL_DEFAULTS  # noqa: E402
from ronin.providers.openai_compat import KNOWN_BASE_URLS  # noqa: E402
from ronin.providers.registry import ADAPTERS  # noqa: E402
from ronin.providers.router import Role  # noqa: E402
from ronin.safety.policy import Decision  # noqa: E402
from ronin.safety.settings import (  # noqa: E402
    LAYER_NAMES,
    LOCAL_SETTINGS,
    PROJECT_SETTINGS,
    RULES_KEY,
    SCALAR_KEYS,
    USER_SETTINGS,
)
from ronin.telemetry import (  # noqa: E402
    CONSENT_RELATIVE_PATH,
    DISCLOSURE,
    DURATION_BOUNDS,
    PAYLOAD_FIELDS,
    SENT_LOG_RELATIVE_PATH,
    TURN_BOUNDS,
    Consent,
    DurationBucket,
    Outcome,
    TaskCategory,
    TaxonomyClass,
    TurnBucket,
)
from ronin.tools.base import ToolContext  # noqa: E402
from ronin.tools.registry import ToolRegistry, build_registry  # noqa: E402
from ronin.tools.shell import PersistentShell, ShellSession  # noqa: E402
from ronin.tools.task import SubagentType  # noqa: E402
from ronin.verify.checkpoints import CHECKPOINT_DIR  # noqa: E402

#: First line of every generated page. Present so a hand edit is visibly doomed.
MARKER = (
    "<!-- generated by docs/site/generate.py — do not edit by hand. "
    "Run: python docs/site/generate.py -->"
)

#: Pages this script owns. Anything else in ``docs/site/`` is hand-written.
GENERATED_PAGES: tuple[str, ...] = (
    "tools.md",
    "config.md",
    "hooks.md",
    "subagents.md",
    "providers.md",
    "telemetry.md",
)


# --------------------------------------------------------------------------- #
# The registry, built offline
# --------------------------------------------------------------------------- #


async def _no_fetch(url: str) -> tuple[str, str]:
    """Stand-in fetcher. Never called: the generator only reads specs."""
    raise NotImplementedError(url)


async def _no_extract(html: str, url: str) -> str:
    raise NotImplementedError(url)


async def _no_search(query: str) -> Sequence[Mapping[str, str]]:
    raise NotImplementedError(query)


def _no_subagent(prompt: str, subagent: SubagentType) -> Awaitable[str]:
    raise NotImplementedError(subagent.name)


def full_registry(root: Path) -> ToolRegistry:
    """Every tool a session can have, assembled without touching anything.

    ``build_registry`` gates each tool group behind a dependency, so documenting the
    full set means supplying one of each. None of them is ever invoked here — the page
    is rendered from ``ToolSpec``s — and ``PersistentShell`` does not spawn ``bash``
    until ``start()``, so this stays a pure in-memory construction.
    """
    ctx = ToolContext(root=root, env={})
    return build_registry(
        ctx,
        shell=ShellSession(shell=PersistentShell(cwd=root, env={})),
        subagent_runner=_no_subagent,
        fetch=_no_fetch,
        extract=_no_extract,
        search=_no_search,
        clock=lambda: 0.0,
    )


def cli_registry(root: Path) -> ToolRegistry:
    """The tools a plain ``python -m ronin`` session gets, derived the same way it is.

    ``ronin.cli.wire.build_runtime`` wires a shell and — *unconditionally* — a fetcher and
    extractor, so ``web_fetch`` is in every CLI session; ``ronin.session.build_session``
    then adds ``task``. ``web_search`` is deliberately absent here: ``build_runtime`` adds
    it only when a search provider is configured (``RONIN_SEARCH_PROVIDER``), which a bare
    session has not set, so a bare CLI session has no ``web_search``. Mirroring
    ``build_runtime`` here rather than hardcoding a list is what keeps the "in a plain
    session?" column true after someone changes the wiring. None of these callables is
    invoked — the page is rendered from ``ToolSpec``s — so the ``_no_*`` sentinels are safe.
    """
    ctx = ToolContext(root=root, env={})
    return build_registry(
        ctx,
        shell=ShellSession(shell=PersistentShell(cwd=root, env={})),
        fetch=_no_fetch,
        extract=_no_extract,
        clock=lambda: 0.0,
    )


#: Added by ``ronin.session.build_session`` after ``build_registry`` returns, because
#: ``TaskTool`` needs a runner that needs a registry that contains ``TaskTool``.
SESSION_ADDED_TOOLS: tuple[str, ...] = ("task",)


# --------------------------------------------------------------------------- #
# Rendering helpers
# --------------------------------------------------------------------------- #


def _page(title: str, intro: str, body: Sequence[str]) -> str:
    """One page: marker, H1, intro paragraph, then body lines. Trailing newline."""
    lines = [MARKER, "", f"# {title}", "", intro.strip(), "", *body]
    text = "\n".join(lines).rstrip("\n")
    return text + "\n"


def _table(headers: Sequence[str], rows: Sequence[Sequence[str]]) -> list[str]:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    out.extend("| " + " | ".join(cell for cell in row) + " |" for row in rows)
    return out


def _cell(text: str) -> str:
    """Make a string safe inside a markdown table cell, deterministically."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _schema_lines(spec: ToolSpec) -> list[str]:
    """One line per argument, from the tool's real JSON Schema."""
    schema = spec.json_schema
    properties = schema.get("properties")
    if not isinstance(properties, Mapping) or not properties:
        return ["_takes no arguments._"]
    required = schema.get("required")
    required_names = set(required) if isinstance(required, list) else set()
    rows: list[list[str]] = []
    for name in properties:
        entry = properties[name]
        detail = entry if isinstance(entry, Mapping) else {}
        kind = str(detail.get("type", "any"))
        note = str(detail.get("description", ""))
        rows.append(
            [
                f"`{name}`",
                kind,
                "yes" if name in required_names else "no",
                _cell(note),
            ]
        )
    return _table(("argument", "type", "required", "meaning"), rows)


# --------------------------------------------------------------------------- #
# tools.md
# --------------------------------------------------------------------------- #

TOOLS_INTRO = """
Every tool a session can hold, generated from `ronin.tools.registry.build_registry`.
The description text below each heading is the *exact* string sent to the model —
`Tool.describe()` renders it, in a fixed order (summary, when to use, when not to
use, worked examples), because a description that only says what a tool does gets
called in situations it should not be.

A session does not necessarily have all of these. `build_registry` gates each group
behind a dependency: no shell means no `bash`, no fetcher means no `web_fetch`. A
tool that is absent is invisible to the model, which is strictly better than one that
exists and always errors. `--mode plan` narrows the set further, to read-only tools
only, and re-derives that property from the specs rather than trusting a prompt.

`danger level` decides what the permission gate does with a call: `read_only` never
asks, and anything higher can be gated by a rule in `.ronin/settings.json`. See
[config.md](config.md).
"""


def render_tools() -> str:
    registry = full_registry(ROOT)
    specs = sorted(registry.specs(), key=lambda spec: spec.name)
    in_cli = {spec.name for spec in cli_registry(ROOT).specs()} | set(SESSION_ADDED_TOOLS)
    needs_injection = [spec.name for spec in specs if spec.name not in in_cli]
    body: list[str] = [
        f"{len(specs)} tools, listed alphabetically.",
        "",
        *_table(
            ("tool", "danger level", "approval by default", "in a plain session?"),
            [
                [
                    f"[`{spec.name}`](#{spec.name})",
                    spec.danger_level.name.lower(),
                    "yes" if spec.requires_approval else "no",
                    "yes" if spec.name in in_cli else "no — needs a search provider",
                ]
                for spec in specs
            ],
        ),
        "",
        "The last column is derived, not asserted: `ronin.cli.wire.build_runtime` wires "
        "the shell and — unconditionally — a fetcher and extractor, so `web_fetch` is "
        "present in every CLI session; `ronin.session.build_session` then adds "
        + ", ".join(f"`{name}`" for name in SESSION_ADDED_TOOLS)
        + ". "
        + (
            ", ".join(f"`{name}`" for name in needs_injection)
            + " is the one tool a bare `python -m ronin` session does **not** have: it "
            "appears only when a search provider is configured (`RONIN_SEARCH_PROVIDER`), "
            "because a search tool with no backend that errors on every call teaches the "
            "model to keep trying it"
            if needs_injection
            else "every tool below is present in a `python -m ronin` session"
        )
        + ". Web content that does arrive — from `web_fetch` or `web_search` — is "
        "registered with the taint tracker and surfaced as untrusted data, not obeyed as "
        "instructions; see [config.md](config.md).",
        "",
    ]
    for spec in specs:
        body.extend(
            [
                f"## {spec.name}",
                "",
                f"`danger_level` `{spec.danger_level.name.lower()}` "
                f"({int(spec.danger_level)} of {int(max(DangerLevel))}) · "
                f"`requires_approval` `{str(spec.requires_approval).lower()}`",
                "",
                "### arguments",
                "",
                *_schema_lines(spec),
                "",
                "### description, as the model receives it",
                "",
                "```text",
                *spec.description.splitlines(),
                "```",
                "",
            ]
        )
    return _page("tool reference", TOOLS_INTRO, body)


# --------------------------------------------------------------------------- #
# config.md
# --------------------------------------------------------------------------- #

CONFIG_INTRO = """
Generated from `ronin.safety.settings` and `ronin.cli.spine.Paths`, so the layer
order documented here is the order the loader actually applies and the paths are the
ones a session actually reads.

Two merge rules, and they are deliberately not the same:

* **Scalars override.** If the project says `mode: auto_edit` and you pass
  `--mode ask`, you meant ask.
* **Rule lists append.** A later layer can only ever *add* a rule. If a layer
  replaced the list, a project `settings.json` with one convenience rule would
  silently discard every builtin rule beneath it — including the tool-wide `ask` that
  is the shell's floor — and nothing would error. To defeat an earlier rule you write
  a more specific one, which stays visible in `python -m ronin doctor`.

One malformed layer does not stop the session. The layer is skipped, the problem is
recorded, and `python -m ronin doctor` names the file and the reason. An unknown key is an
error too: a silently ignored typo is a permission the user believes they granted.
"""


def render_config() -> str:
    layer_paths = {
        "builtin": "(compiled in)",
        "user": f"`~/{USER_SETTINGS.as_posix()}`",
        "project": f"`<workspace>/{PROJECT_SETTINGS.as_posix()}`",
        "local": f"`<workspace>/{LOCAL_SETTINGS.as_posix()}`",
        "flags": "(this invocation only)",
    }
    body: list[str] = [
        "## layers, lowest precedence first",
        "",
        *_table(
            ("order", "layer", "where"),
            [
                [str(index + 1), f"`{name}`", layer_paths.get(name, "—")]
                for index, name in enumerate(LAYER_NAMES)
            ],
        ),
        "",
        f"`{LOCAL_SETTINGS.as_posix()}` is the only one that must stay out of git: it "
        "is the layer that holds machine-local overrides. The other files under "
        f"`{RONIN_DIRNAME}/` are meant to be committed and shared, which is why a "
        f"blanket `{RONIN_DIRNAME}/` line in `.gitignore` is a misconfiguration "
        "`python -m ronin doctor` reports and offers a patch for.",
        "",
        "## settings keys",
        "",
        "Every key a settings file may contain. Anything else is an error naming the "
        "key, not a silent ignore.",
        "",
        *_table(
            ("key", "type"),
            [[f"`{key}`", f"`{kind}`"] for key, kind in sorted(SCALAR_KEYS.items())],
        ),
        "",
        f"…plus `{RULES_KEY}`, a list of permission rules (below).",
        "",
        f"`mode` is one of {', '.join(f'`{mode.value}`' for mode in Mode)}. "
        f"`default_decision` is one of "
        f"{', '.join(f'`{decision.value}`' for decision in Decision)}.",
        "",
        "A `count_or_null` key takes a positive integer, or `null` for no limit. "
        "`max_retained_paths` and `max_retained_chars` bound what compaction keeps "
        "in full when it folds the middle of a long session: the most recent tool "
        "result per file path. Both default to no limit, which is what makes a file "
        "edited early still readable hundreds of turns later — the cost is that a "
        "session touching more files than the window can hold stays above the "
        "compaction trigger and says so. Bounding either one trades that guarantee "
        "for fitting. `compaction_escalate` lets compaction make that trade by "
        "itself when the fold still would not fit the window, naming every path it "
        "gives up; it is off by default, because an over-budget transcript is a "
        "reported problem and a dropped file is a silent one.",
        "",
        "## a rule",
        "",
        "Two spellings are accepted: the nested one is precise, the flat one is what "
        "people actually type.",
        "",
        "```json",
        "{",
        '  "rules": [',
        '    {"tool": "bash", "decision": "allow",',
        '     "match": {"kind": "regex", "pattern": "^pytest"}},',
        '    {"tool": "bash", "decision": "allow", "command": "^ruff check"},',
        '    {"tool": "write", "decision": "deny", "path": "migrations/**",',
        '     "reason": "migrations are reviewed by hand", "always_ask": true}',
        "  ]",
        "}",
        "```",
        "",
        *_table(
            ("field", "meaning"),
            [
                ["`tool`", "tool name, or `*` for every tool. Defaults to `*`."],
                [
                    "`decision`",
                    "one of " + ", ".join(f"`{decision.value}`" for decision in Decision) + ".",
                ],
                [
                    "`match`",
                    "`{kind: tool}` (any use), `{kind: exact, argument, value}`, "
                    "`{kind: path, pattern, argument}`, or "
                    "`{kind: regex, pattern}`.",
                ],
                ["`command`", "shorthand for a `regex` match on the command argument."],
                ["`path`", "shorthand for a `path` match."],
                ["`reason`", "shown to the user when the rule decides. Free text."],
                [
                    "`always_ask`",
                    "the rule cannot be waived by a more permissive mode. "
                    "`unwaivable` is accepted as an alias.",
                ],
            ],
        ),
        "",
        "## every path a session touches",
        "",
        "Derived from `ronin.cli.spine.Paths`. `<workspace>` is the git repository "
        "root when there is one, otherwise the working directory.",
        "",
        *_table(
            ("what", "path"),
            [
                ["project settings", f"`<workspace>/{PROJECT_SETTINGS.as_posix()}`"],
                ["local settings (gitignored)", f"`<workspace>/{LOCAL_SETTINGS.as_posix()}`"],
                ["user settings", f"`~/{USER_SETTINGS.as_posix()}`"],
                ["hooks", f"`<workspace>/{RONIN_DIRNAME}/{HOOKS_FILENAME}`"],
                ["subagents", f"`<workspace>/{AGENTS_SUBDIR.as_posix()}/*.md`"],
                ["slash commands", f"`<workspace>/{COMMANDS_SUBDIR.as_posix()}/*.md`"],
                ["MCP servers", f"`<workspace>/{MCP_CONFIG_RELATIVE_PATH}`"],
                ["session transcripts", f"`<workspace>/{SESSIONS_SUBDIR}`"],
                ["checkpoints", f"`<workspace>/{CHECKPOINT_DIR}`"],
                ["repo-map cache", f"`<workspace>/{CACHE_SUBDIR.as_posix()}`"],
                ["telemetry consent", f"`~/{CONSENT_RELATIVE_PATH.as_posix()}`"],
                ["telemetry audit log", f"`~/{SENT_LOG_RELATIVE_PATH.as_posix()}`"],
            ],
        ),
        "",
        "`python -m ronin doctor` prints all of these with their real values, plus which layer "
        "set each scalar. Prefer it to reading this table.",
    ]
    return _page("config reference", CONFIG_INTRO, body)


# --------------------------------------------------------------------------- #
# hooks.md
# --------------------------------------------------------------------------- #

HOOKS_INTRO = f"""
Generated from `ronin.agents.hooks`. A hook is a shell command the session runs when
something happens. It gets the event as JSON on stdin, and what it does with its exit
code is the whole feature.

The exit-code contract is the part people get wrong, so it is stated first:

* **exit 0** — fine. Anything on stdout is context the model can be shown.
* **exit {BLOCK_EXIT_CODE}** — *block*. The action does not happen and stderr becomes
  the reason the model is told. This is the load-bearing case: it is how a team
  enforces "never touch `migrations/`" without patching Ronin.
* **any other non-zero** — a warning. The action proceeds. A hook that exits 1 because
  `prettier` is not installed must not stop the agent from working; if every failure
  blocked, one broken hook would wedge every session, and the first thing a user does
  with a wedged agent is delete all their hooks.

A timeout is a warning too, for the same reason — with one opt-in exception,
`block_on_timeout`, for the hook whose whole purpose is to refuse.
"""


def render_hooks() -> str:
    body: list[str] = [
        "## the five events",
        "",
        *_table(
            ("event", "when it fires", "can block?"),
            [
                [
                    f"`{event.value}`",
                    _cell(_HOOK_WHEN[event]),
                    "yes" if event in BLOCKING_EVENTS else "no",
                ]
                for event in HookEvent
            ],
        ),
        "",
        "Blocking only makes sense before the fact. "
        + ", ".join(f"`{event.value}`" for event in HookEvent if event not in BLOCKING_EVENTS)
        + " all fire after the thing has happened — the file is already written — so "
        f"an exit {BLOCK_EXIT_CODE} there is reported as a warning rather than a "
        "block that would be a lie told after the fact.",
        "",
        "Only "
        + ", ".join(f"`{event.value}`" for event in HookEvent if event in TOOL_EVENTS)
        + f" carry a tool name, so `matcher` is only meaningful for those two. It "
        f"defaults to `{MATCH_ALL}`, and a matcher on any other event is a config "
        "error rather than a rule that silently never matches.",
        "",
        "## outcomes",
        "",
        *_table(
            ("outcome", "meaning"),
            [[f"`{outcome.value}`", _cell(_HOOK_OUTCOME[outcome])] for outcome in HookOutcome],
        ),
        "",
        f"## `{RONIN_DIRNAME}/{HOOKS_FILENAME}`",
        "",
        "```json",
        "{",
        '  "PreToolUse": [',
        "    {",
        '      "matcher": "write|edit|multi_edit",',
        '      "hooks": [',
        '        {"command": "scripts/protect-migrations.sh", "timeout": 5,',
        '         "name": "no-migrations", "block_on_timeout": true}',
        "      ]",
        "    }",
        "  ],",
        '  "PostToolUse": [',
        "    {",
        '      "matcher": "edit|write",',
        '      "hooks": [{"command": "npx prettier --write $(jq -r .arguments.path)"}]',
        "    }",
        "  ],",
        '  "SessionStart": [',
        '    {"hooks": [{"command": "git rev-parse --abbrev-ref HEAD"}]}',
        "  ]",
        "}",
        "```",
        "",
        *_table(
            ("key", "default", "meaning"),
            [
                ["`command`", "—", "required. Run through the shell."],
                [
                    "`matcher`",
                    f"`{MATCH_ALL}`",
                    "`|`-separated glob patterns matched against the tool name.",
                ],
                [
                    "`timeout`",
                    f"`{DEFAULT_TIMEOUT_SECONDS}` seconds",
                    "on expiry the whole process *group* is killed, so a hook that "
                    "backgrounds `npm test` cannot outlive its own timeout.",
                ],
                [
                    "`block_on_timeout`",
                    "`false`",
                    "treat a timeout as a block. For a policy check that must fail closed.",
                ],
                [
                    "`name`",
                    "—",
                    "cosmetic, but it is what appears in the block reason. "
                    '"no-migrations blocked this" beats "hook 2 blocked this".',
                ],
            ],
        ),
        "",
        "## the payload on stdin",
        "",
        "Keys are sorted, so a hook's behaviour is reproducible.",
        "",
        "```json",
        event_payload(
            HookEvent.PRE_TOOL_USE,
            tool_name="write",
            data={"arguments": {"path": "src/app.py"}},
        ),
        "```",
        "",
        "For an event with no tool, the `tool_name` key is absent rather than null:",
        "",
        "```json",
        event_payload(HookEvent.SESSION_START),
        "```",
        "",
        "## output caps",
        "",
        f"Each stream is capped at {MAX_HOOK_OUTPUT_CHARS:,} characters, with a marker "
        "naming what was cut. A hook that prints its whole test suite must not push "
        'the transcript out of the context window on its way to saying "ok".',
        "",
        "## a hook that blocks, end to end",
        "",
        "```sh",
        "#!/bin/sh",
        "# .ronin/hooks/protect-migrations.sh — exit 2 to refuse the edit.",
        "path=$(jq -r '.arguments.path // empty')",
        'case "$path" in',
        "  migrations/*)",
        '    echo "migrations/ is reviewed by hand; propose the SQL instead" >&2',
        f"    exit {BLOCK_EXIT_CODE}",
        "    ;;",
        "esac",
        "exit 0",
        "```",
        "",
        "The message on stderr is what the model is told, so write it as an "
        "instruction the model can act on — not as a log line.",
    ]
    return _page("hooks", HOOKS_INTRO, body)


#: Prose for each event. Hand-written because "when it fires" is intent, which no
#: introspection recovers — but keyed by the enum, so a new event breaks the render
#: with a ``KeyError`` instead of quietly going undocumented.
_HOOK_WHEN: Mapping[HookEvent, str] = {
    HookEvent.PRE_TOOL_USE: "before a tool runs, with the arguments the model chose",
    HookEvent.POST_TOOL_USE: "after a tool returns, with its result",
    HookEvent.USER_PROMPT_SUBMIT: "when a prompt is submitted, before the model sees it",
    HookEvent.STOP: "when the turn finishes",
    HookEvent.SESSION_START: "once, when the session opens",
}

_HOOK_OUTCOME: Mapping[HookOutcome, str] = {
    HookOutcome.OK: "exit 0; stdout may be shown to the model as context",
    HookOutcome.WARN: (
        "non-zero and not the block code, or a timeout: the action proceeds and the user is told"
    ),
    HookOutcome.BLOCK: (
        f"exit {BLOCK_EXIT_CODE} on a blocking event: the action does not happen and "
        "stderr becomes the model's reason"
    ),
}


# --------------------------------------------------------------------------- #
# subagents.md
# --------------------------------------------------------------------------- #

SUBAGENTS_INTRO = f"""
Generated from `ronin.agents.definitions`. A subagent is a description plus a tool
list plus a system prompt — a document, not code — so it lives in
`{AGENTS_SUBDIR.as_posix()}/<name>.md` with frontmatter, and a team adds one by
adding a file. Four are shipped in code and any of them can be replaced by a file of
the same `name`.

Why a subagent at all: it runs with a *fresh context window* and a *narrower tool
set*, and the parent only ever sees its final message. That makes it the right shape
for work that would otherwise flood the main transcript — reading forty search hits
to answer one question — and the wrong shape for anything where the parent needs the
intermediate steps.

The frontmatter parser is stdlib, and malformed frontmatter is a named error with a
line number, never a skip. The failure being prevented is specific: someone writes
`tool:` instead of `tools:`, the agent loads with no tools, and what the user *sees*
is the model being unhelpful — no error, nothing to search for.
"""


def render_subagents() -> str:
    body: list[str] = [
        "## frontmatter keys",
        "",
        *_table(
            ("key", "required", "meaning"),
            [
                [
                    f"`{key}`",
                    "yes" if key in REQUIRED_KEYS else "no",
                    _cell(_AGENT_KEY_DOC[key]),
                ]
                for key in KNOWN_KEYS
            ],
        ),
        "",
        "An unknown key is an error naming the file and the line. So are a duplicate "
        "key, an illegal name, an unclosed fence and an empty body.",
        "",
        f"`model` names a **role**, not a model id: one of "
        f"{', '.join(f'`{role}`' for role in sorted(MODEL_ROLES))}. The router "
        "resolves it (see [providers.md](providers.md)). It is restricted to roles on "
        "purpose — validating a concrete model id here would need provider knowledge "
        "in a layer that must not have it, and an unvalidated model id is a runtime "
        "404 at the worst possible moment.",
        "",
        "## a definition file",
        "",
        "```markdown",
        "---",
        "name: migration-reviewer",
        "description: Reviews database migrations for irreversible operations.",
        "tools: [read, glob, grep]",
        "model: fast",
        "max_iterations: 8",
        "---",
        "",
        "You review database migrations and you cannot change anything.",
        "",
        "Report every operation that cannot be rolled back, with file:line.",
        "```",
        "",
        "`tools:` accepts `[a, b]`, `a, b`, or a `- item` block list.",
        "",
        "## the four builtins",
        "",
        *_table(
            ("name", "model role", "tools", "write paths", "max iterations"),
            [
                [
                    f"`{definition.name}`",
                    f"`{definition.model}`" if definition.model else "session default",
                    ", ".join(f"`{tool}`" for tool in definition.tools),
                    (
                        ", ".join(f"`{glob}`" for glob in definition.write_paths)
                        if definition.write_paths
                        else "unrestricted"
                    ),
                    str(definition.max_iterations),
                ]
                for definition in BUILTIN_AGENTS.values()
            ],
        ),
        "",
    ]
    for definition in BUILTIN_AGENTS.values():
        body.extend(
            [
                f"### {definition.name}",
                "",
                definition.description,
                "",
                "System prompt, as the subagent receives it:",
                "",
                "```text",
                *definition.system_prompt.splitlines(),
                "```",
                "",
            ]
        )
    body.extend(
        [
            "## path restriction is a mechanism, not a request",
            "",
            f"`write_paths` wraps every mutating tool "
            f"({', '.join(f'`{name}`' for name in MUTATING_TOOL_NAMES)}) in a "
            "guard that resolves each path argument and refuses anything outside the "
            "allowed globs, returning a failed tool result that names the roots it "
            "*may* write to.",
            "",
            'This is why `test-writer` cannot touch `src/`. A prompt saying "only '
            'write tests" is a preference; a model told not to edit edits three '
            "turns later. Read tools are deliberately not wrapped — a subagent "
            "reading outside its lane costs context, not correctness.",
            "",
            "## dispatch",
            "",
            "The model normally names the type it wants: "
            '`task(subagent_type="explorer", ...)`. Selection by task description is '
            "only a fallback for a caller that has a description and no name, and it "
            "returns nothing rather than guessing below a floor — a wrong subagent "
            "(fresh context, wrong tools, confident answer) is worse than no "
            "subagent.",
            "",
            "`python -m ronin doctor` lists the subagents a workspace actually loaded, which is "
            "the fastest way to find out that a file did not parse.",
        ]
    )
    return _page("subagents", SUBAGENTS_INTRO, body)


_AGENT_KEY_DOC: Mapping[str, str] = {
    "name": "what the model types as `subagent_type`. Lowercase, digits, `-`, `_`.",
    "description": "the only thing the dispatcher has to decide when to invoke it.",
    "tools": "the tool names this agent gets. A name the registry does not have is an error.",
    "model": "a router *role*, not a model id. Empty means the subagent default.",
    "write_paths": "globs this agent may write inside. Enforced by a tool wrapper.",
    "max_iterations": "how many turns it may take before it must report. Defaults to 20.",
}


# --------------------------------------------------------------------------- #
# providers.md
# --------------------------------------------------------------------------- #

PROVIDERS_INTRO = """
Generated from `ronin.providers.registry.ADAPTERS` and
`ronin.providers.openai_compat.KNOWN_BASE_URLS`. Every provider on this page has a
real implementation in this checkout; nothing is listed aspirationally.

Config is TOML because `tomllib` is in the standard library and the file is
hand-edited. Two sections: `[roles]` maps a *role* to a model name, and
`[models.<name>]` says what that model is.

The rule the role system encodes: **never burn the main model on grep triage.** A
subagent summarizing forty search hits and a compaction pass rewriting history are
both mechanical work, so the role is part of the request and the model is part of the
config. `Router.for_subagent()` and `Router.for_compaction()` take no role argument
at all, so those two callers cannot get it wrong by forgetting one.

A key is never written in the config file — `api_key_env` names an environment
variable instead, because a config file with a secret in it ends up in a git history.
"""


def render_providers() -> str:
    grouped: dict[str, list[str]] = {}
    for name, builder in ADAPTERS.items():
        grouped.setdefault(builder.__name__, []).append(name)
    body: list[str] = [
        "## roles",
        "",
        *_table(
            ("role", "what routes here"),
            [[f"`{role.value}`", _cell(_ROLE_DOC[role])] for role in Role],
        ),
        "",
        "`main` is required. A config that omits `fast` routes mechanical work to the "
        "main model and still *works* — falling back beats crashing mid-session — and "
        "the fallback is visible in the ledger, where a `fast` row naming the main "
        "model is the signal to fix the config.",
        "",
        "## providers with a real adapter",
        "",
        *_table(
            ("`provider =`", "wire protocol", "default base url", "key from"),
            [
                [
                    f"`{name}`",
                    _cell(_PROTOCOL_DOC[builder_name]),
                    f"`{KNOWN_BASE_URLS[name]}`" if name in KNOWN_BASE_URLS else "—",
                    _cell(_KEY_DOC[builder_name]),
                ]
                for builder_name, names in sorted(grouped.items())
                for name in sorted(names)
            ],
        ),
        "",
        "One entry per *wire protocol*, not per vendor — which is why several hosts "
        "share a single adapter. Adding a provider that speaks one of these protocols "
        "is a TOML stanza and no code.",
        "",
        "## setup, per provider",
        "",
    ]
    for builder_name in sorted(grouped):
        body.extend(
            [
                f"### {_PROTOCOL_TITLE[builder_name]}",
                "",
                "Reached by "
                + ", ".join(f'`provider = "{name}"`' for name in sorted(grouped[builder_name]))
                + ".",
                "",
                *_SETUP[builder_name],
                "",
            ]
        )
    body.extend(
        [
            "## local models, and what they cost you in capability",
            "",
            "There are two local paths, and they are different in kind:",
            "",
            "* **A local OpenAI-compatible server** — Ollama, LM Studio, vLLM, "
            "llama.cpp. Ronin talks HTTP to `localhost`; the server owns the weights. "
            "This needs the `http` extra (`pip install 'ronin[http]'`) because that is "
            "the only place a real socket is opened.",
            "* **In-process MLX** — Apple silicon only, no server, no port, no second "
            "copy of the weights in RAM. `mlx_lm` is imported inside the streaming "
            "call, so `import ronin.providers` stays free on Linux and in CI.",
            "",
            "Local builds default to "
            f"`native_tools = {str(LOCAL_DEFAULTS.native_tools).lower()}`, "
            f"`parallel_tools = {str(LOCAL_DEFAULTS.parallel_tools).lower()}`, "
            f"`max_context = {LOCAL_DEFAULTS.max_context:,}`. Narrow on purpose: base "
            "Qwen, Hermes and most local GGUF/MLX builds have no tool-calling head, "
            "and promising native tools we do not have produces a turn where the model "
            "chats about calling a tool and nothing happens. Without native tools the "
            "router puts the model behind a format shim automatically, from its "
            "capabilities — a human deciding per-model whether to wrap is a human who "
            "will eventually forget.",
            "",
            "A build that *does* have a tool-calling head says so in config:",
            "",
            "```toml",
            "[models.local-qwen]",
            'provider = "mlx"',
            'model = "mlx-community/Qwen2.5-Coder-7B-Instruct-4bit"',
            "native_tools = true",
            "```",
            "",
            "## capability overrides",
            "",
            "Any of these may be set per model, and a partial override is merged "
            "against the adapter's defaults — a config saying only "
            "`native_tools = false` does not have to restate `max_context`.",
            "",
            *_table(
                ("key", "meaning"),
                [
                    ["`native_tools`", "the model has a real tool-calling API."],
                    ["`parallel_tools`", "it can request several tools in one turn."],
                    ["`prompt_cache`", "the provider bills cached prefix tokens cheaper."],
                    ["`thinking`", "it emits a separate reasoning stream."],
                    ["`max_context`", "context window in tokens."],
                    ["`vision`", "it accepts image blocks."],
                ],
            ),
            "",
            "## prices",
            "",
            "`price_in`, `price_out` and `price_cache_read` are per-million-token "
            "prices you write in the config, and they are what the ledger multiplies. "
            "Ronin ships **no** price table: a hardcoded price goes stale silently and "
            "then every cost figure in the session is wrong with no warning. A model "
            "with no prices set is recorded as unpriced — flagged, not treated as "
            "free.",
            "",
            "## verifying a setup without spending anything",
            "",
            "```sh",
            "python -m ronin doctor",
            "```",
            "",
            "It checks that the configured role resolves to a defined model and that "
            "the named key variable is actually present in the environment. It does "
            "**not** call the provider: a diagnostic that hangs for thirty seconds is "
            "a diagnostic people stop running.",
        ]
    )
    return _page("provider setup", PROVIDERS_INTRO, body)


_ROLE_DOC: Mapping[Role, str] = {
    Role.MAIN: "the session's own reasoning and code writing. Required.",
    Role.PLAN: "plan mode, where nothing may mutate. Falls back to `main`.",
    Role.FAST: "subagents and history compaction. Falls back to `main`.",
}

_PROTOCOL_TITLE: Mapping[str, str] = {
    "_build_anthropic": "Anthropic",
    "_build_openai_compat": "OpenAI-compatible (including every local server)",
    "_build_moonshot": "Moonshot / Kimi",
    "_build_mlx": "MLX, in-process on Apple silicon",
    "_build_local_adapter_entry": "the fine-tuned adapter, in-process and offline",
}

_PROTOCOL_DOC: Mapping[str, str] = {
    "_build_anthropic": "Anthropic messages API",
    "_build_openai_compat": "OpenAI chat-completions",
    "_build_moonshot": "Moonshot (OpenAI-shaped, vendor quirks handled)",
    "_build_mlx": "in-process, no HTTP at all",
    "_build_local_adapter_entry": "in-process; picks mlx or transformers for you",
}

_KEY_DOC: Mapping[str, str] = {
    "_build_anthropic": "`api_key_env`",
    "_build_openai_compat": "`api_key_env`, or nothing for a keyless local server",
    "_build_moonshot": "`api_key_env`",
    "_build_mlx": "no key; the weights are on disk",
    "_build_local_adapter_entry": "no key, ever — this is the $0 lane",
}

_SETUP: Mapping[str, tuple[str, ...]] = {
    "_build_anthropic": (
        "```toml",
        "[roles]",
        'main = "sonnet"',
        "",
        "[models.sonnet]",
        'provider = "anthropic"',
        'model = "<the model id your account has>"',
        'api_key_env = "ANTHROPIC_API_KEY"',
        "```",
        "",
        "Needs the `http` extra and `ANTHROPIC_API_KEY` in the environment. "
        "`base_url` defaults to the public API and only needs setting for a proxy.",
    ),
    "_build_local_adapter_entry": (
        "The fine-tuned adapter, served from local weights. **No API key, no network, "
        "no cost** — which makes it the only lane that can run the eval suite under a "
        "$0 budget, and the reason the whole offline path exists.",
        "",
        "```toml",
        "[roles]",
        'main = "ronin-qwen-local"',
        "# Point every role at it, not just main: a config that routes `fast` to a",
        "# hosted model needs a key, which defeats the purpose.",
        'plan = "ronin-qwen-local"',
        'fast = "ronin-qwen-local"',
        "",
        "[models.ronin-qwen-local]",
        'provider = "local-adapter"',
        'model = "Qwen/Qwen2.5-Coder-1.5B-Instruct"',
        "```",
        "",
        "The backend is chosen for you — `mlx_lm` on Apple silicon, `transformers` "
        "elsewhere — and `RONIN_LOCAL_BACKEND` overrides it. Set `RONIN_ADAPTER` to a "
        "trained checkpoint directory to serve the fine-tune; leave it unset to run "
        "the bare base model.",
        "",
        "A checkpoint that has a config but no weights is **refused at startup** "
        "rather than silently falling back to the base model. Serving the base when "
        "the adapter was asked for produces a number that reads as a measurement of "
        "the fine-tune and is not one.",
        "",
        "The adapter itself teaches *ronin-native behaviour* — tool syntax, gate "
        "handling, recovery, planning. It does **not** add coding knowledge, and a "
        "1.5B model is not a substitute for a frontier one on hard tasks.",
    ),
    "_build_openai_compat": (
        "This one adapter covers hosted providers and every local server, because "
        "they speak the same protocol. A hosted one needs a key; a local one usually "
        "does not.",
        "",
        "```toml",
        "[roles]",
        'main = "hosted"',
        'fast = "local"',
        "",
        "[models.hosted]",
        'provider = "deepseek"          # base_url is filled in from the table above',
        'model = "<the model id>"',
        'api_key_env = "DEEPSEEK_API_KEY"',
        "",
        "[models.local]",
        'provider = "ollama"            # http://localhost:11434/v1',
        'model = "<whatever `ollama list` shows>"',
        "native_tools = false",
        "```",
        "",
        "A provider name that is not in the defaults table must set `base_url` "
        "itself; an OpenAI-compatible endpoint has to say where it is, and guessing "
        "would produce a connection error pointing at the wrong host.",
    ),
    "_build_moonshot": (
        "```toml",
        "[roles]",
        'main = "kimi"',
        "",
        "[models.kimi]",
        'provider = "moonshot"',
        'model = "<the model id your account has>"',
        'api_key_env = "MOONSHOT_API_KEY"',
        "```",
        "",
        "Needs the `http` extra. `base_url` has a default and only needs setting for "
        "a regional endpoint.",
    ),
    "_build_mlx": (
        "Apple silicon only, and it needs `mlx-lm` installed. No key, no server, no "
        "port — generation happens in this process, which is the whole reason the "
        "adapter exists: going through a local HTTP server would cost a subprocess, a "
        "port, and a second copy of the weights in RAM on a machine where RAM is the "
        "binding constraint.",
        "",
        "```toml",
        "[roles]",
        'main = "local-qwen"',
        "",
        "[models.local-qwen]",
        'provider = "mlx"',
        'model = "mlx-community/Qwen2.5-Coder-7B-Instruct-4bit"',
        'adapter_path = ""   # a trained LoRA adapter directory, if you have one',
        "```",
        "",
        "On Linux or Windows this adapter cannot run — `mlx_lm` is Apple-silicon-only. "
        "Use a local OpenAI-compatible server instead.",
    ),
}


# --------------------------------------------------------------------------- #
# telemetry.md
# --------------------------------------------------------------------------- #

TELEMETRY_INTRO = f"""
Generated from `ronin.telemetry`. **Telemetry is off by default and sends nothing
until you opt in.** This page exists so you can check that claim against the code
rather than believing it.

The disclosure shown once, on first run, verbatim:

> {DISCLOSURE}
"""


def render_telemetry() -> str:
    body: list[str] = [
        *_telemetry_wiring_note(),
        "## the entire payload",
        "",
        "This is not a summary. `ronin.telemetry.TaskOutcome` is a frozen dataclass "
        "with exactly these fields, every one an enum, a validated version string or "
        "a bool, and `serialize()` emits exactly these keys — a test asserts the "
        "serialized key set equals the allowlist, so adding a field breaks the build.",
        "",
        *_table(
            ("field", "type", "values"),
            [
                [
                    "`ronin_version`",
                    "string",
                    "dotted digits, or `unknown`. Pattern-checked, so a local "
                    "version like `1.0.0+dirty.branch-name` becomes `unknown` rather "
                    "than carrying a branch name onto the wire.",
                ],
                [
                    "`python_version`",
                    "string",
                    "`major.minor` only. The patch level is dropped: it narrows the "
                    "population and answers nothing.",
                ],
                ["`os_name`", "enum", "`linux`, `macos`, `windows`, `other`"],
                [
                    "`task_category`",
                    "enum",
                    ", ".join(f"`{value.value}`" for value in TaskCategory),
                ],
                ["`outcome`", "enum", ", ".join(f"`{value.value}`" for value in Outcome)],
                [
                    "`taxonomy_class`",
                    "enum",
                    ", ".join(f"`{value.value}`" for value in TaxonomyClass),
                ],
                ["`turn_bucket`", "enum", ", ".join(f"`{value.value}`" for value in TurnBucket)],
                [
                    "`duration_bucket`",
                    "enum",
                    ", ".join(f"`{value.value}`" for value in DurationBucket),
                ],
                ["`gate_denied`", "bool", "whether a permission gate denied a call"],
            ],
        ),
        "",
        "The serialized key set, in full: "
        + ", ".join(f"`{name}`" for name in PAYLOAD_FIELDS)
        + ".",
        "",
        "## bucket boundaries",
        "",
        "Half-open `[lo, hi)`, so a turn that took exactly 5 seconds is `5-15s`.",
        "",
        *_table(
            ("turns", "bucket"),
            [
                *(
                    [
                        f"{_lower_turn(index)}-{upper - 1}"
                        if upper - 1 > _lower_turn(index)
                        else f"{upper - 1}",
                        f"`{bucket.value}`",
                    ]
                    for index, (upper, bucket) in enumerate(TURN_BOUNDS)
                ),
                [f"{TURN_BOUNDS[-1][0]} and up", f"`{TurnBucket.SIXTEEN_PLUS.value}`"],
            ],
        ),
        "",
        *_table(
            ("seconds", "bucket"),
            [
                *(
                    [
                        f"{_lower_duration(index)} <= t < {upper:g}",
                        f"`{bucket.value}`",
                    ]
                    for index, (upper, bucket) in enumerate(DURATION_BOUNDS)
                ),
                [
                    f"t >= {DURATION_BOUNDS[-1][0]:g}",
                    f"`{DurationBucket.OVER_5M.value}`",
                ],
            ],
        ),
        "",
        "## what is deliberately not collected",
        "",
        *_table(
            ("not collected", "why"),
            [
                [
                    "prompts, model output",
                    "the entire point of the product is that people type their real "
                    "work into it. There is no aggregation of prompt text that is "
                    "safe, so there is no field for it.",
                ],
                [
                    "code, diffs, filenames, paths",
                    "a path leaks the repository layout and often the employer; a "
                    "filename leaks the feature under development; a diff is the code.",
                ],
                [
                    "commands",
                    "`bash` arguments contain hostnames, ticket ids, credentials "
                    "typed by mistake, and the shape of someone's infrastructure.",
                ],
                [
                    "task ids",
                    "Ronin's task and eval-case ids are user-authored. "
                    "`fix-acme-corp-sso-timeout` is a customer name and a security "
                    "incident in one string — free text wearing an identifier's "
                    "clothes.",
                ],
                [
                    "any machine / user / install / session id",
                    "no uuid is minted. Two payloads from one machine are "
                    "indistinguishable from two machines, which costs per-user rates "
                    "and buys the inability to build a per-user profile.",
                ],
                [
                    "timestamps",
                    "a precise send time pins working hours and, joined with a git "
                    "history, a person.",
                ],
                [
                    "exact counts and durations",
                    "`1247.318s` is a near-unique fingerprint; `1-5m` answers the "
                    "only question anyone asks of it.",
                ],
            ],
        ),
        "",
        "## consent",
        "",
        *_table(
            ("state", "sends?", "how you get here"),
            [
                [
                    f"`{Consent.UNASKED.value}`",
                    "no",
                    "the default. Not a soft yes — nothing is sent in any state but `granted`.",
                ],
                [f"`{Consent.GRANTED.value}`", "yes", "you ran the opt-in command."],
                [
                    f"`{Consent.REFUSED.value}`",
                    "no",
                    "you opted out. **Sticky** — nothing re-prompts, ever.",
                ],
            ],
        ),
        "",
        f"The record lives at `~/{CONSENT_RELATIVE_PATH.as_posix()}` — per user, not "
        "per project, because a refusal that only sticks in one checkout is not a "
        "refusal.",
        "",
        "A consent file that cannot be read or parsed resolves to `refused` with the "
        "disclosure already marked shown. That fails closed in both directions at "
        "once: a corrupted file can neither cause a send nor cause a re-prompt. A "
        "user who had opted in silently stops being recorded, which is the safe "
        "direction to fail in.",
        "",
        "## auditing instead of trusting",
        "",
        f"Every payload handed to the sender is appended, as the exact wire JSON, to "
        f"`~/{SENT_LOG_RELATIVE_PATH.as_posix()}`. Read the file, or print it:",
        "",
        "```sh",
        "ronin2 telemetry show",
        "```",
        "",
        "The line is written *before* the send is attempted, so a crash mid-send still "
        "leaves a record. That means a logged line proves the payload was handed to "
        "the sender, not that it arrived — the log can over-report what left the "
        "machine, never under-report it.",
        "",
        "## turning it off, and the failure modes",
        "",
        "```sh",
        "ronin2 telemetry off      # sticky; nothing re-prompts",
        "ronin2 telemetry status   # the current state and both file paths",
        "```",
        "",
        "The module cannot slow or break a turn. It has no `httpx` import and opens no "
        "socket — the transport is a callable injected by the caller. A send is "
        "bounded by a timeout, and a sender that raises, hangs or returns nonsense "
        "produces a recorded failure and nothing else: telemetry that can break a "
        "session is worse than no telemetry.",
    ]
    return _page("telemetry", TELEMETRY_INTRO, body)


#: Whether ``ronin2 telemetry …`` exists in this build. Probed rather than
#: assumed: the module ships the consent machinery and the disclosure text, and the CLI
#: subcommand that drives it is a separate change. A page that documents a subcommand
#: which does not parse is exactly the failure this generator exists to prevent, and
#: probing means the caveat disappears by itself the moment the command lands.
def telemetry_command_wired() -> bool:
    return "telemetry" in {member.value for member in CliCommand}


def _telemetry_wiring_note() -> list[str]:
    if telemetry_command_wired():
        return []
    return [
        "## the `telemetry` subcommand is not wired in this build",
        "",
        "`ronin.cli.main.Command` has no `telemetry` member yet, so "
        "`ronin2 telemetry on` does **not** parse in this checkout. Every "
        "command spelled that way on this page — and in the first-run disclosure — "
        "describes the intended surface, and this section is generated by probing the "
        "parser, so it disappears on its own when the command lands.",
        "",
        "Until then, the two files *are* the interface, which is the point of keeping them plain:",
        "",
        "```sh",
        "# opt in  (equivalent of `telemetry on`)",
        f"mkdir -p ~/{CONSENT_RELATIVE_PATH.parent.as_posix()}",
        f'printf \'{{"disclosed": true, "schema": 1, "state": "granted"}}\\n\' '
        f"> ~/{CONSENT_RELATIVE_PATH.as_posix()}",
        "",
        "# opt out (equivalent of `telemetry off`) — sticky, nothing re-prompts",
        f'printf \'{{"disclosed": true, "schema": 1, "state": "refused"}}\\n\' '
        f"> ~/{CONSENT_RELATIVE_PATH.as_posix()}",
        "",
        "# audit   (equivalent of `telemetry show`)",
        f"cat ~/{SENT_LOG_RELATIVE_PATH.as_posix()} 2>/dev/null || echo 'nothing has been sent'",
        "```",
        "",
        "Nothing is sent in this build regardless: the CLI passes no sender, and "
        "`record()` with no sender returns `no_sender` without touching the network. "
        "The consent file is what will be honoured once one is wired.",
        "",
    ]


def _lower_turn(index: int) -> int:
    return 1 if index == 0 else TURN_BOUNDS[index - 1][0]


def _lower_duration(index: int) -> str:
    return "0" if index == 0 else f"{DURATION_BOUNDS[index - 1][0]:g}"


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #


def render_all() -> dict[str, str]:
    """Every generated page, keyed by filename. The one source of truth for staleness."""
    rendered = {
        "tools.md": render_tools(),
        "config.md": render_config(),
        "hooks.md": render_hooks(),
        "subagents.md": render_subagents(),
        "providers.md": render_providers(),
        "telemetry.md": render_telemetry(),
    }
    missing = set(GENERATED_PAGES) - set(rendered)
    extra = set(rendered) - set(GENERATED_PAGES)
    if missing or extra:
        raise SystemExit(
            f"GENERATED_PAGES disagrees with render_all(): missing {sorted(missing)}, "
            f"unexpected {sorted(extra)}"
        )
    return rendered


def stale(directory: Path | None = None) -> list[str]:
    """Filenames whose contents on disk differ from what the code now renders."""
    target = SITE if directory is None else directory
    out: list[str] = []
    for name, body in render_all().items():
        path = target / name
        # Bytes, not text: read_text applies universal-newline translation and would
        # hide a CRLF regression in a file this script writes with newline="\n".
        current = path.read_bytes() if path.exists() else b""
        if current != body.encode("utf-8"):
            out.append(name)
    return out


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="generate docs/site reference pages")
    parser.add_argument("--check", action="store_true", help="exit 1 if any page is stale")
    args = parser.parse_args(list(argv) if argv is not None else None)

    drifted = stale()
    if args.check:
        if drifted:
            sys.stderr.write(
                "docs/site pages are STALE: "
                + ", ".join(sorted(drifted))
                + "\nrun: python docs/site/generate.py\n"
            )
            return 1
        print(f"docs/site: {len(GENERATED_PAGES)} generated page(s) up to date")
        return 0

    for name, body in render_all().items():
        (SITE / name).write_text(body, encoding="utf-8", newline="\n")
    print(f"wrote {len(GENERATED_PAGES)} page(s) to {SITE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
