"""GBNF grammar for Ronin's tool-call dialect — llama.cpp-style constrained
decoding, generated from the SAME canonical spec as the renderer and parser.

With the grammar active, the sampler *cannot* emit a malformed ``<tool_call>``
block: tags, name-first key order, and JSON-typed argument values are enforced
token-by-token, independent of model quality. This is the runtime's second,
model-independent path to valid tool JSON (the first being a corpus that
teaches the right shape).

Documented constraint: in grammar mode, prose may not contain the ``<``
character outside a tool-call block (the grammar needs an unambiguous block
start). Ronin's final answers rarely need a bare ``<``; the flag can always be
turned off (``RONIN_GRAMMAR=0``).

Backends: llama.cpp supports GBNF (``LlamaGrammar``); MLX does not — the
embedded provider skips the grammar there and says so rather than faking it.
"""
from __future__ import annotations

import json
import re

from . import CALL_SHAPE_RE, parse_tool_calls

# Standard GBNF JSON value rules (llama.cpp json.gbnf lineage), namespaced so
# they can't collide if a caller concatenates grammars.
_JSON_RULES = r"""
rj-object ::= "{" rj-ws ( rj-string rj-ws ":" rj-ws rj-value ( rj-ws "," rj-ws rj-string rj-ws ":" rj-ws rj-value )* )? rj-ws "}"
rj-array  ::= "[" rj-ws ( rj-value ( rj-ws "," rj-ws rj-value )* )? rj-ws "]"
rj-value  ::= rj-object | rj-array | rj-string | rj-number | "true" | "false" | "null"
rj-string ::= "\"" ( [^"\\\x00-\x1f] | "\\" ( ["\\/bfnrt] | "u" [0-9a-fA-F] [0-9a-fA-F] [0-9a-fA-F] [0-9a-fA-F] ) )* "\""
rj-number ::= "-"? ( "0" | [1-9] [0-9]* ) ( "." [0-9]+ )? ( [eE] [-+]? [0-9]+ )?
rj-ws     ::= [ \t\n]*
"""


def grammar_for_tools(tool_names: list[str] | None = None) -> str:
    """The GBNF grammar text constraining output to Ronin's dialect.

    ``tool_names`` (e.g. the 13 registry names) locks the ``name`` field to an
    exact alternation — a hallucinated tool name becomes unsamplable. With no
    names given, any ``[a-z_]+`` name is allowed (the CALL_SHAPE_RE contract).
    """
    if tool_names:
        for n in tool_names:
            if not re.fullmatch(r"[a-z_]+", n):
                raise ValueError(f"tool name {n!r} outside the dialect's [a-z_]+ contract")
        name_rule = " | ".join(f'"\\"{n}\\""' for n in sorted(set(tool_names)))
    else:
        name_rule = '"\\"" [a-z_]+ "\\""'
    return (
        "# Ronin tool-call dialect — generated by ronin_dialect.gbnf (do not hand-edit)\n"
        "root      ::= prose? ( tool-call rj-ws prose? )*\n"
        'prose     ::= [^<]+\n'
        'tool-call ::= "<tool_call>" rj-ws body rj-ws "</tool_call>"\n'
        'body      ::= "{" rj-ws "\\"name\\"" rj-ws ":" rj-ws tool-name rj-ws "," rj-ws '
        '"\\"arguments\\"" rj-ws ":" rj-ws rj-object rj-ws "}"\n'
        f"tool-name ::= {name_rule}\n"
        + _JSON_RULES
    )


def conforms(text: str, tool_names: list[str] | None = None) -> bool:
    """Pure-Python membership check for the grammar's language — the offline
    twin of the sampler-side constraint, used by tests and by callers that want
    to verify output without a llama.cpp backend. PURE."""
    # every '<' must start a well-formed <tool_call> block
    cursor = 0
    while True:
        lt = text.find("<", cursor)
        if lt == -1:
            break
        if not text.startswith("<tool_call>", lt):
            return False
        end = text.find("</tool_call>", lt)
        if end == -1:
            return False
        cursor = end + len("</tool_call>")
    clean, calls = parse_tool_calls(text)
    if "<tool_call>" in text and not calls:
        return False                      # blocks present but none parsed = malformed
    for chunk in re.findall(r"<tool_call>(.*?)</tool_call>", text, re.DOTALL):
        if not CALL_SHAPE_RE.search(chunk):
            return False                  # wrong key order / name shape
        obj = json.loads(chunk.strip())
        if not isinstance(obj.get("arguments"), dict):
            return False                  # grammar forces OBJECT arguments
        if tool_names is not None and obj.get("name") not in tool_names:
            return False                  # name outside the locked alternation
    return True


__all__ = ["grammar_for_tools", "conforms"]
