"""Build the launch panda as **ASCII character art** (not half-blocks).

Converts a real panda image into a brightness-ramp ASCII drawing — so it's made
of plain text characters yet still reads as a panda (ears, eye patches, body,
paws). Writes ``panda_ascii.py`` with the art as a string.

Run:  python packages/cli/tools/build_ascii_panda.py /tmp/panda/panda_new.png
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build_panda as b  # reuse ffmpeg→PPM + flood-fill background removal

WIDTH = 46
RAMP = "@%#*+=-:. "   # dark → light (black panda features become dense glyphs)


def build(src: Path) -> str:
    ppm = b.to_ppm(src, WIDTH)
    w, h, px = b.parse_ppm(ppm)
    transp = b.background_mask(w, h, px)
    w, h, px, transp = b.crop(w, h, px, transp)
    lines = []
    for y in range(0, h, 2):                 # every other row → ~2:1 char aspect
        row = []
        for x in range(w):
            i = y * w + x
            if transp[i]:
                row.append(" ")
            else:
                r, g, bl = px[i]
                lum = (r * 299 + g * 587 + bl * 114) // 1000
                row.append(RAMP[lum * (len(RAMP) - 1) // 255])
        lines.append("".join(row).rstrip())
    # trim fully-blank top/bottom lines
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(lines)


def main() -> None:
    src = Path(sys.argv[1] if len(sys.argv) > 1 else "/tmp/panda/panda_new.png")
    art = build(src)
    out = Path(__file__).resolve().parents[1] / "src" / "ro_claude_kit_cli" / "panda_ascii.py"
    body = ('"""Auto-generated by tools/build_ascii_panda.py — a real panda as ASCII\n'
            'character art. Do not edit by hand; re-run the builder."""\n\n'
            'PANDA_ASCII = r"""\n' + art + '\n"""\n')
    out.write_text(body)
    print(art)
    print(f"\nwrote {out}  ({len(art.splitlines())} rows)")


if __name__ == "__main__":
    main()
