"""Lights Out — a 5x5 grid of lights; toggling a cell flips it *and* its four
orthogonal neighbors. Goal: turn every light off. Move a cursor with the arrow
keys and press space/enter to toggle the cursor cell. The start is generated by
applying random toggles to an all-off board, so it is *always* solvable.

The rules live in pure, I/O-free functions (``toggle``, ``is_solved``,
``make_puzzle``) so they can be unit-tested without a terminal; ``_play`` drives
them via the real-time plumbing in ``_realtime``. On a non-TTY (tests / piped
stdin) we fall back to a typed ``row col`` prompt rather than crashing.
"""
from __future__ import annotations

import random

from rich.console import Console

from ._engine import GameMeta, header, ask_line
from . import _realtime as rt

N = 5            # board is N x N
SCRAMBLES = 8    # random toggles applied to build a solvable start

# Orthogonal stencil: the pressed cell plus its 4 neighbors.
_STENCIL = ((0, 0), (-1, 0), (1, 0), (0, -1), (0, 1))


# ---------------------------------------------------------------------------
# Pure rules (no I/O) — tests depend on these names/signatures.
# ---------------------------------------------------------------------------
def toggle(grid: list[list[int]], r: int, c: int) -> list[list[int]]:
    """Return a NEW grid with cell ``(r, c)`` and its 4 orthogonal neighbors
    flipped (0<->1). Out-of-bounds neighbors are skipped, so it is bounds-safe.
    The input grid is left unmodified."""
    rows = len(grid)
    cols = len(grid[0]) if rows else 0
    out = [row[:] for row in grid]
    for dr, dc in _STENCIL:
        nr, nc = r + dr, c + dc
        if 0 <= nr < rows and 0 <= nc < cols:
            out[nr][nc] ^= 1
    return out


def is_solved(grid: list[list[int]]) -> bool:
    """True when every light is off (the whole grid is zero)."""
    return all(cell == 0 for row in grid for cell in row)


def make_puzzle(rng: random.Random, n: int = 5, scrambles: int = 8) -> list[list[int]]:
    """Build a solvable ``n x n`` start: begin all-off, then apply ``scrambles``
    random toggles using the supplied ``random.Random``. Because toggling is its
    own inverse and the presses commute, replaying that same set of presses
    returns the board to all-off — i.e. a solution always exists."""
    grid = [[0] * n for _ in range(n)]
    for _ in range(scrambles):
        r = rng.randrange(n)
        c = rng.randrange(n)
        grid = toggle(grid, r, c)
    return grid


# ---------------------------------------------------------------------------
# Raw ANSI palette (Rich markup does NOT render in raw/fullscreen mode).
# ---------------------------------------------------------------------------
_AMBER = "\x1b[1;38;2;224;175;104m"   # bright amber — a lit cell
_MUTE = "\x1b[38;2;107;112;137m"      # dim slate — an off cell / chrome
_GREEN = "\x1b[1;38;2;158;206;106m"   # win
_TEAL = "\x1b[38;2;45;212;191m"
_BOLD = "\x1b[1m"
_RESET = "\x1b[0m"
# cursor cell: teal background. Lit-under-cursor uses a bright fill (the block
# hides the background, so brightness — not the bg — signals the cursor there);
# off-under-cursor shows dim dots on the visible teal background.
_CUR_BG = "\x1b[48;2;45;212;191m"
_CUR_LIT = "\x1b[1;38;2;245;245;245m"
_CUR_OFF = "\x1b[38;2;15;23;42m"


def _cell(on: int, *, cursor: bool) -> str:
    """Return the 2-char glyph for one cell. lit = amber █, off = dim ·."""
    glyph = "██" if on else "··"
    if cursor:
        fg = _CUR_LIT if on else _CUR_OFF
        return f"{_CUR_BG}{fg}{glyph}{_RESET}"
    colour = _AMBER if on else _MUTE
    return f"{colour}{glyph}{_RESET}"


def _frame(grid: list[list[int]], cur: tuple[int, int], moves: int, *,
           status: str, won: bool = False) -> str:
    n = len(grid)
    lit = sum(sum(row) for row in grid)
    lines = [
        f"  {_AMBER}\U0001f4a1 Lights Out{_RESET}   "
        f"{_MUTE}lit {lit:>2}{_RESET}   "
        f"{_MUTE}moves {moves}{_RESET}",
        "",
        f"   {_MUTE}┌{'─' * (n * 3 + 1)}┐{_RESET}",
    ]
    for r in range(n):
        cells = [_cell(grid[r][c], cursor=(not won and (r, c) == cur))
                 for c in range(n)]
        lines.append(f"   {_MUTE}│{_RESET} " + " ".join(cells)
                     + f" {_MUTE}│{_RESET}")
    lines.append(f"   {_MUTE}└{'─' * (n * 3 + 1)}┘{_RESET}")
    lines.append("")
    if status:
        lines.append("  " + status)
    else:
        lines.append(f"  {_MUTE}arrows move · space/enter toggle · "
                     f"q quit{_RESET}")
    return "\n".join(lines)


def _new_board(rng: random.Random) -> list[list[int]]:
    """A fresh, solvable board that is not already solved (so there's a game)."""
    grid = make_puzzle(rng, N, SCRAMBLES)
    while is_solved(grid):
        grid = make_puzzle(rng, N, SCRAMBLES)
    return grid


def _play(console: Console) -> None:
    header(console, GAME)

    if not rt.is_interactive():
        _play_fallback(console)
        return

    rng = random.Random()
    grid = _new_board(rng)
    cur = (N // 2, N // 2)
    moves = 0
    won = False
    quit_now = False

    rt.enter_fullscreen()
    try:
        with rt.raw_mode():
            while True:
                if won:
                    status = (f"{_GREEN}\U0001f3c6 Lights out in {moves} moves "
                              f"— you win!{_RESET}  {_MUTE}press any key{_RESET}")
                    rt.draw(_frame(grid, cur, moves, status=status, won=True))
                    rt.read_key()
                    break

                rt.draw(_frame(grid, cur, moves, status=""))
                key = rt.read_key()
                if key in ("q", "esc"):
                    quit_now = True
                    break
                if key == "up":
                    cur = (max(0, cur[0] - 1), cur[1])
                elif key == "down":
                    cur = (min(N - 1, cur[0] + 1), cur[1])
                elif key == "left":
                    cur = (cur[0], max(0, cur[1] - 1))
                elif key == "right":
                    cur = (cur[0], min(N - 1, cur[1] + 1))
                elif key in ("space", "enter"):
                    grid = toggle(grid, cur[0], cur[1])
                    moves += 1
                    if is_solved(grid):
                        won = True
    finally:
        rt.exit_fullscreen()

    if quit_now:
        console.print(f"  [#6b7089]bye — {moves} moves in[/#6b7089]\n")
    else:
        console.print(f"  [bold #9ece6a]\U0001f3c6 Lights out in {moves} moves "
                      f"— you win![/bold #9ece6a]\n")


# ---------------------------------------------------------------------------
# Typed fallback for non-TTY environments (tests / piped stdin).
# ---------------------------------------------------------------------------
def _render_plain(console: Console, grid: list[list[int]]) -> None:
    """Rich-markup render for the non-interactive typed fallback."""
    n = len(grid)
    head = "      " + " ".join(str(c) for c in range(n))
    console.print(f"  [dim]{head}[/dim]")
    for r in range(n):
        cells = ["[bold #e0af68]█[/bold #e0af68]" if grid[r][c]
                 else "[dim]·[/dim]" for c in range(n)]
        console.print(f"  [dim]{r:>2}[/dim]    " + " ".join(cells))
    console.print()


def _play_fallback(console: Console) -> None:
    rng = random.Random()
    grid = _new_board(rng)
    n = len(grid)
    moves = 0
    console.print(f"  [dim]{n}x{n} grid — toggling a cell flips it and its 4 "
                  f"neighbors. Type \"row col\" (0-{n - 1}) to toggle. q to quit."
                  f"[/dim]\n")
    _render_plain(console, grid)

    while True:
        raw = ask_line(console, "row col:")
        low = raw.lower()
        if low in ("q", "quit", ""):
            console.print("\n  [dim]gg![/dim]")
            return
        parts = low.split()
        if len(parts) != 2 or not (parts[0].isdigit() and parts[1].isdigit()):
            console.print("  [yellow]format: row col  (e.g. 2 3)[/yellow]")
            continue
        r, c = int(parts[0]), int(parts[1])
        if not (0 <= r < n and 0 <= c < n):
            console.print(f"  [yellow]row/col must be 0-{n - 1}[/yellow]")
            continue
        grid = toggle(grid, r, c)
        moves += 1
        _render_plain(console, grid)
        if is_solved(grid):
            console.print(f"  [bold #9ece6a]\U0001f3c6 Lights out in {moves} "
                          f"moves — you win![/bold #9ece6a]")
            return


GAME = GameMeta(key="lights", name="Lights Out", emoji="\U0001f4a1",
                desc="toggle the grid until every light is off", play=_play)
