"""Generate a .gitignore from built-in templates — `ronin gitignore`.

`ronin gitignore python node macos` assembles a clean, de-duplicated .gitignore
from curated per-stack templates — offline, no gitignore.io round-trip. The
template assembly is pure and unit-tested.
"""
from __future__ import annotations

_TEMPLATES: dict[str, list[str]] = {
    "python": ["__pycache__/", "*.py[cod]", "*.egg-info/", ".eggs/", "build/", "dist/",
               ".venv/", "venv/", "env/", ".pytest_cache/", ".mypy_cache/", ".ruff_cache/",
               ".coverage", "htmlcov/", "*.so", ".tox/"],
    "node": ["node_modules/", "npm-debug.log*", "yarn-error.log", ".pnpm-debug.log",
             "dist/", "build/", ".next/", ".nuxt/", "coverage/", "*.tsbuildinfo"],
    "java": ["*.class", "target/", "*.jar", "*.war", "build/", ".gradle/", "out/"],
    "go": ["*.exe", "*.test", "*.out", "bin/", "vendor/", "go.work.sum"],
    "rust": ["target/", "Cargo.lock", "**/*.rs.bk"],
    "ruby": ["*.gem", ".bundle/", "vendor/bundle", "log/", "tmp/", "Gemfile.lock"],
    "php": ["vendor/", "composer.lock", ".phpunit.result.cache"],
    "dotnet": ["bin/", "obj/", "*.user", "*.suo", ".vs/"],
    "swift": [".build/", "*.xcodeproj/xcuserdata/", "DerivedData/", "Packages/"],
    "macos": [".DS_Store", ".AppleDouble", "._*", ".Spotlight-V100", ".Trashes"],
    "windows": ["Thumbs.db", "ehthumbs.db", "Desktop.ini", "$RECYCLE.BIN/", "*.lnk"],
    "linux": ["*~", ".fuse_hidden*", ".directory", ".Trash-*"],
    "vscode": [".vscode/*", "!.vscode/settings.json", "!.vscode/extensions.json"],
    "jetbrains": [".idea/", "*.iml", "*.iws", "out/"],
    "env": [".env", ".env.local", ".env.*.local", "*.key", "*.pem", "secrets.json"],
    "logs": ["*.log", "logs/"],
    "ronin": [".ronin/"],
}

# friendly aliases
_ALIASES = {"py": "python", "js": "node", "javascript": "node", "typescript": "node",
            "ts": "node", "golang": "go", "rb": "ruby", "cs": "dotnet", "csharp": "dotnet",
            "c#": "dotnet", "osx": "macos", "mac": "macos", "win": "windows",
            "idea": "jetbrains", "intellij": "jetbrains", "code": "vscode",
            "dotenv": "env", "secrets": "env"}


def available() -> list[str]:
    """All known template names. Pure."""
    return sorted(_TEMPLATES)


def gitignore_for(stacks: list[str]) -> str:
    """Assemble a de-duplicated .gitignore for the given stacks/aliases. Unknown
    names are skipped. Pure."""
    out: list[str] = ["# Generated by ronin"]
    seen: set[str] = set()
    used: list[str] = []
    for raw in stacks:
        key = _ALIASES.get(raw.strip().lower(), raw.strip().lower())
        if key not in _TEMPLATES or key in used:
            continue
        used.append(key)
        out.append("")
        out.append(f"# {key}")
        for pat in _TEMPLATES[key]:
            if pat not in seen:
                seen.add(pat)
                out.append(pat)
    return "\n".join(out) + "\n"
