"""Turn any REST endpoint into an agent tool — `ronin plugin from-api`.

Give it a name, a URL (with ``{placeholders}`` that become tool parameters), and
optionally which JSON fields to extract (dotted paths like ``data.0.title``), and
ronin generates a complete, crash-proof plugin file. No other coding agent lets
you mint a tool from an arbitrary API in one command — this is what makes the
plugin library effectively unlimited. The generation is pure and unit-tested.
"""
from __future__ import annotations

import keyword
import re

_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")
_PLACEHOLDER_RE = re.compile(r"\{([a-zA-Z_]\w*)\}")


def valid_name(name: str) -> bool:
    """A tool name must be a lowercase identifier, not a keyword. Pure."""
    n = (name or "").strip()
    return bool(_NAME_RE.match(n)) and not keyword.iskeyword(n)


def url_params(url: str) -> list[str]:
    """Ordered, de-duplicated ``{placeholder}`` names in a URL. Pure."""
    seen: list[str] = []
    for m in _PLACEHOLDER_RE.finditer(url or ""):
        if m.group(1) not in seen:
            seen.append(m.group(1))
    return seen


def generate_api_plugin(name: str, url: str, *, fields: list[str] | None = None,
                        blurb: str = "", method: str = "GET") -> str:
    """Generate a complete plugin source that calls ``url`` and extracts ``fields``.

    ``{placeholders}`` in the URL become required string parameters; remaining
    parameters are passed as query params. Pure — returns Python source."""
    if not valid_name(name):
        raise ValueError(f"invalid tool name '{name}' — use lowercase letters/digits/underscore")
    params = url_params(url)
    fields = fields or []
    desc = (blurb or f"Call the {name} API.").replace('"', "'")

    sig = ", ".join(f"{p}: str" for p in params) if params else ""
    props = ", ".join(f'"{p}": {{"type": "string"}}' for p in params)
    required = ", ".join(f'"{p}"' for p in params)
    # extraction block
    if fields:
        field_lines = ", ".join(f'"{f.split(".")[-1]}": _get(data, "{f}")' for f in fields)
        extract = f"return {{{field_lines}}}"
    else:
        extract = "return data if isinstance(data, dict) else {\"data\": data}"

    return f'''# ronin plugin (generated by `ronin plugin from-api`): {name}
from __future__ import annotations

import httpx
from ronin_agent_patterns import Tool


def _get(obj, path):
    for part in path.split("."):
        if isinstance(obj, list):
            try:
                obj = obj[int(part)]
            except (ValueError, IndexError):
                return None
        elif isinstance(obj, dict):
            obj = obj.get(part)
        else:
            return None
    return obj


def {name}({sig}) -> dict:
    url = "{url}".format({", ".join(f"{p}={p}" for p in params)})
    try:
        r = httpx.request("{method.upper()}", url, timeout=20, follow_redirects=True)
        data = r.json()
    except Exception as e:  # noqa: BLE001
        return {{"error": str(e)}}
    {extract}


def register_tools():
    return [Tool(
        name="{name}",
        description="{desc}",
        input_schema={{"type": "object", "properties": {{{props}}}{f', "required": [{required}]' if required else ""}}},
        handler={name},
    )]
'''
