"""The ronin launch panda — a real panda rendered as truecolor half-block art.

The pixels live in ``panda_pixels.py`` (generated by ``tools/build_panda.py``
from an actual panda image). Each character holds two vertical pixels via
foreground/background colour, so it reads as a real panda — not ASCII guesswork.
Background pixels are transparent, so the panda floats next to the wordmark.
"""
from __future__ import annotations

import sys

from rich.console import Console

try:
    from .panda_pixels import PANDA_LINES
except Exception:  # pragma: no cover - art is always shipped
    PANDA_LINES = ["  ʕ•ᴥ•ʔ  "]


def _panda_text():
    from rich.text import Text
    return Text.from_markup("\n".join(PANDA_LINES))


def _lockup():
    """Panda on the left, the RONIN gradient wordmark beside it, vertically centred."""
    from rich.table import Table

    from .banner import _W as _RW, _banner_text

    grid = Table.grid(padding=(0, 4))
    grid.add_column(vertical="middle")
    grid.add_column(vertical="middle")
    grid.add_row(_panda_text(), _banner_text(_RW))
    return grid


def render_panda(console: Console, *, animate: bool = True) -> None:
    """Print the panda + RONIN lockup."""
    console.print(_lockup())
