"""The ronin launch panda — a *dancing* panda rendered in half-block art.

Four frames generated from shapes (see ``tools/build_panda_face.py``): a round
white face with the signature dark eye-patches, plus a body that sways and arms
that wave. On a TTY we animate through the frames briefly via ``rich.Live``,
then settle on the arms-up frame beside the gradient RONIN wordmark. On a
non-TTY (pipe, CI), we just print the settled frame.
"""
from __future__ import annotations

import sys
import time

from rich.console import Console

# Four dance frames. Each frame is the same width (so the lockup doesn't
# jitter). Generated by ``packages/cli/tools/build_panda_face.py`` — don't edit
# by hand; re-run the generator if you tweak the shapes.
PANDA_FRAMES: tuple[str, ...] = (
    # frame 0 — head leans left, left arm up, right arm down/out
    "      ▄▄█▄▄             ▄▄█▄▄\n"
    "     ███████           ███████\n"
    "    ▀████████▄▄▄▄█▄▄▄▄████████▀\n"
    "     ▀███████████████████████▀\n"
    "       ▄███▀▀ ▀▀███▀▀ ▀▀███▄\n"
    "      ▄███▀     ▀█▀     ▀███▄\n"
    "      ████    ▄  █  ▄    ████\n"
    "     ▀████   ▀█▀ █ ▀█▀   ████▀\n"
    "      █████     ███     █████\n"
    "       ██████▄█▀   ▀█▄██████\n"
    "       █████████▄▄▄███████▀\n"
    "        ███████████████▀▀\n"
    "        █████  ▄▄█▄█▄▄▄▄\n"
    "        ██████████████████▄\n"
    "         ▀██████████████████\n"
    "          ▀█████████████████████▄\n"
    "           ▀███████████████▀██████▄\n"
    "             ▀▀█████████▀▀   ▀▀▀█▀\n"
    "             ▄███▄ ▀ ▄███▄\n"
    "             █████   █████\n"
    "              ▀█▀     ▀█▀",
    # frame 1 — arms up, head centred (the cute "yay!" pose; static fallback)
    "       ▄▄█▄▄             ▄▄█▄▄\n"
    "      ███████           ███████\n"
    "     ▀████████▄▄▄▄█▄▄▄▄████████▀\n"
    "      ▀███████████████████████▀\n"
    "        ▄███▀▀ ▀▀███▀▀ ▀▀███▄\n"
    "       ▄███▀     ▀█▀     ▀███▄\n"
    "       ████    ▄  █  ▄    ████\n"
    "      ▀████   ▀█▀ █ ▀█▀   ████▀\n"
    "       █████     ███     █████\n"
    "      ▄███████▄█▀   ▀█▄███████▄\n"
    "      ███████████▄▄▄███████████\n"
    "       █████▀███████████▀█████\n"
    "       █████  ▄▄▄▄█▄▄▄▄  █████\n"
    "       ███████████████████████\n"
    "        ▀███████████████████▀\n"
    "         ▀█████████████████▀\n"
    "          ▀███████████████▀\n"
    "            ▀▀█████████▀▀\n"
    "            ▄███▄ ▀ ▄███▄\n"
    "            █████   █████\n"
    "             ▀█▀     ▀█▀",
    # frame 2 — head leans right, right arm up, left arm down/out
    "        ▄▄█▄▄             ▄▄█▄▄\n"
    "       ███████           ███████\n"
    "      ▀████████▄▄▄▄█▄▄▄▄████████▀\n"
    "       ▀███████████████████████▀\n"
    "         ▄███▀▀ ▀▀███▀▀ ▀▀███▄\n"
    "        ▄███▀     ▀█▀     ▀███▄\n"
    "        ████    ▄  █  ▄    ████\n"
    "       ▀████   ▀█▀ █ ▀█▀   ████▀\n"
    "        █████     ███     █████\n"
    "         ██████▄█▀   ▀█▄██████\n"
    "          ▀███████▄▄▄█████████\n"
    "            ▀▀███████████████\n"
    "             ▄▄▄▄█▄█▄▄  █████\n"
    "          ▄██████████████████\n"
    "         ██████████████████▀\n"
    "    ▄█████████████████████▀\n"
    "  ▄██████▀███████████████▀\n"
    "   ▀█▀▀▀   ▀▀█████████▀▀\n"
    "           ▄███▄ ▀ ▄███▄\n"
    "           █████   █████\n"
    "            ▀█▀     ▀█▀",
    # frame 3 — arms out wide, head centred
    "       ▄▄█▄▄             ▄▄█▄▄\n"
    "      ███████           ███████\n"
    "     ▀████████▄▄▄▄█▄▄▄▄████████▀\n"
    "      ▀███████████████████████▀\n"
    "        ▄███▀▀ ▀▀███▀▀ ▀▀███▄\n"
    "       ▄███▀     ▀█▀     ▀███▄\n"
    "       ████    ▄  █  ▄    ████\n"
    "      ▀████   ▀█▀ █ ▀█▀   ████▀\n"
    "       █████     ███     █████\n"
    "        ██████▄█▀   ▀█▄██████\n"
    "         ▀███████▄▄▄███████▀\n"
    "           ▀▀███████████▀▀\n"
    "              ▄▄▄▄█▄▄▄▄\n"
    "           ▄█████████████▄\n"
    "          █████████████████\n"
    "     ▄█████████████████████████▄\n"
    "   ▄██████▀███████████████▀██████▄\n"
    "    ▀█▀▀▀   ▀▀█████████▀▀   ▀▀▀█▀\n"
    "            ▄███▄ ▀ ▄███▄\n"
    "            █████   █████\n"
    "             ▀█▀     ▀█▀",
)


def _normalize(frames: tuple[str, ...]) -> tuple[str, ...]:
    """Right-pad every line of every frame to a single shared width so the
    lockup grid doesn't jitter as we cycle frames."""
    width = max(len(line) for frame in frames for line in frame.splitlines())
    return tuple(
        "\n".join(line.ljust(width) for line in frame.splitlines())
        for frame in frames
    )


PANDA_FRAMES = _normalize(PANDA_FRAMES)

# Static still — frame 1 (arms up, centred). Kept as PANDA for backward compat
# with anything that imported the constant by name.
PANDA = PANDA_FRAMES[1]


def _panda_text(idx: int = 1):
    from rich.text import Text
    return Text(PANDA_FRAMES[idx], style="grey85")


def _lockup(idx: int = 1):
    """The dancing panda on the left, the RONIN gradient wordmark beside it."""
    from rich.table import Table

    from .banner import _W as _RW, _banner_text

    grid = Table.grid(padding=(0, 4))
    grid.add_column(vertical="middle")
    grid.add_column(vertical="middle")
    grid.add_row(_panda_text(idx), _banner_text(_RW))
    return grid


_STILL_FRAME = 1            # arms-up — what we settle on
_LOOPS = 2                  # how many times we cycle the 4 frames
_FRAME_DELAY = 0.13         # seconds per frame (~7.7 fps)


def _animate(console: Console) -> None:
    from rich.live import Live

    sequence = list(range(len(PANDA_FRAMES))) * _LOOPS + [_STILL_FRAME]
    with Live(
        _lockup(sequence[0]),
        console=console,
        refresh_per_second=12,
        transient=False,
    ) as live:
        for idx in sequence[1:]:
            time.sleep(_FRAME_DELAY)
            live.update(_lockup(idx))


def render_panda(console: Console) -> None:
    """Print the dancing panda + RONIN wordmark lockup.

    On a TTY we briefly animate through the dance frames and settle on the
    arms-up pose. On a non-TTY (pipes, CI, captured Console) we render the
    settled frame once.
    """
    is_tty = bool(getattr(console, "is_terminal", False)) and sys.stdout.isatty()
    if is_tty:
        try:
            _animate(console)
            return
        except Exception:  # pragma: no cover — fall back to a static print
            pass
    console.print(_lockup(_STILL_FRAME))
