"""The ronin launch panda — a real panda rendered as **ASCII character art**.

The art lives in ``panda_ascii.py`` (generated by ``tools/build_ascii_panda.py``
from a real panda image via a brightness ramp), so it's plain text characters
yet still reads as a panda: round ears, black eye patches, chunky body, paws.
Shown beside the gradient RONIN wordmark.
"""
from __future__ import annotations

from rich.console import Console

try:
    from .panda_ascii import PANDA_ASCII
except Exception:  # pragma: no cover - art is always shipped
    PANDA_ASCII = "  ʕ•ᴥ•ʔ  "


def _panda_text():
    from rich.text import Text
    # soft off-white so the panda's dark features (dense glyphs) read cleanly
    return Text(PANDA_ASCII.strip("\n"), style="grey82")


def _lockup():
    """The ASCII panda on the left, the RONIN gradient wordmark beside it."""
    from rich.table import Table

    from .banner import _W as _RW, _banner_text

    grid = Table.grid(padding=(0, 4))
    grid.add_column(vertical="middle")
    grid.add_column(vertical="middle")
    grid.add_row(_panda_text(), _banner_text(_RW))
    return grid


def render_panda(console: Console) -> None:
    """Print the ASCII panda + RONIN wordmark lockup."""
    console.print(_lockup())
