#!/usr/bin/env python3
"""Regenerate the type-check and lint path lists in ``pyproject.toml`` from disk.

Four lists in ``pyproject.toml`` have to agree with the filesystem: mypy's
``files``, mypy's ``mypy_path``, the per-module override that relaxes
``disallow_untyped_decorators`` for test modules, and ruff's ``include``. All four
were hand-maintained, and the failure is silent in the worst way: a test directory
missing from ``files`` is a directory with **no type checking at all**, and nothing
reports that. The same goes for a test module missing from the override list —
except there the symptom is a spurious error, which at least gets noticed.

The override list has to name modules rather than directories because the test
trees are deliberately *not* packages (making them packages breaks collection
across the rest of the monorepo), so mypy sees ``test_files``, not
``tests.tools.test_files``. mypy rejects a partial-component wildcard like
``test_*``, so the names must be enumerated — which is exactly the kind of list a
human forgets and a script does not.

Usage::

    python scripts/sync_typecheck_paths.py           # rewrite in place
    python scripts/sync_typecheck_paths.py --check    # exit 1 if stale (for CI)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PYPROJECT = ROOT / "pyproject.toml"
SRC = ROOT / "src" / "ronin"
TESTS = ROOT / "tests"

BEGIN = "# >>> generated by scripts/sync_typecheck_paths.py — do not edit by hand"
END = "# <<< generated"


def test_dirs() -> list[str]:
    """Every ``tests/<name>`` directory holding at least one module."""
    found = [
        path.name
        for path in sorted(TESTS.iterdir())
        if path.is_dir() and path.name != "__pycache__" and any(path.glob("*.py"))
    ]
    return found


def test_modules() -> list[str]:
    """Every test module basename, deduplicated.

    Two directories holding the same basename would collide under
    ``explicit_package_bases``; that is a real problem with the non-package test
    layout, so surface it here rather than letting mypy report it obscurely.
    """
    seen: dict[str, str] = {}
    collisions: list[str] = []
    for name in test_dirs():
        for path in sorted((TESTS / name).glob("*.py")):
            stem = path.stem
            if stem in seen and seen[stem] != name:
                collisions.append(f"tests/{seen[stem]}/{stem}.py vs tests/{name}/{stem}.py")
            seen.setdefault(stem, name)
    if collisions:
        raise SystemExit(
            "duplicate test module basenames across non-package test dirs "
            "(mypy would conflate them):\n  " + "\n  ".join(collisions)
        )
    return sorted(seen)


def render() -> str:
    dirs = test_dirs()
    files = ["src/ronin", *(f"tests/{name}" for name in dirs)]
    mypy_path = ":".join(["src", *(f"tests/{name}" for name in dirs)])
    include = ["src/ronin/**/*.py", *(f"tests/{name}/**/*.py" for name in dirs)]
    modules = test_modules()

    def toml_list(values: list[str], indent: str = "    ") -> str:
        return "[\n" + "".join(f'{indent}"{value}",\n' for value in values) + "]"

    return "\n".join(
        [
            BEGIN,
            "[tool.mypy]",
            'python_version = "3.11"',
            f"files = {toml_list(files)}",
            "strict = true",
            "warn_unreachable = true",
            "explicit_package_bases = true",
            f'mypy_path = "{mypy_path}"',
            "",
            "# pytest's @parametrize is an untyped decorator as far as mypy is concerned;",
            "# that is a property of pytest, not a hole in our typing. Enumerated rather",
            "# than wildcarded because mypy rejects a partial-component pattern.",
            "[[tool.mypy.overrides]]",
            f"module = {toml_list(modules)}",
            "disallow_untyped_decorators = false",
            "",
            "# mlx-lm is an Apple-silicon-only optional dependency imported inside a",
            "# function so nothing else in the tree needs it. It ships no stubs and CI is",
            "# Linux, so there is nothing to type against.",
            "[[tool.mypy.overrides]]",
            'module = ["mlx_lm.*"]',
            "ignore_missing_imports = true",
            "",
            "[tool.ruff]",
            "line-length = 100",
            'target-version = "py311"',
            'src = ["src", "tests"]',
            f"include = {toml_list(include)}",
            "",
            "[tool.ruff.lint]",
            'select = ["E", "F", "I", "UP", "B", "SIM", "RUF"]',
            END,
        ]
    )


def splice(text: str, block: str) -> str:
    if BEGIN not in text:
        raise SystemExit(
            f"{PYPROJECT} has no generated block; add the {BEGIN!r} / {END!r} markers first"
        )
    head, _, rest = text.partition(BEGIN)
    _, _, tail = rest.partition(END)
    return f"{head}{block}{tail}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if stale")
    args = parser.parse_args()

    current = PYPROJECT.read_text(encoding="utf-8")
    updated = splice(current, render())
    if current == updated:
        print("pyproject.toml type-check paths are up to date")
        return 0
    if args.check:
        print(
            "pyproject.toml type-check paths are STALE — run "
            "`python scripts/sync_typecheck_paths.py`",
            file=sys.stderr,
        )
        return 1
    PYPROJECT.write_text(updated, encoding="utf-8")
    print(f"rewrote {PYPROJECT.relative_to(ROOT)}: {len(test_dirs())} test dirs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
